services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    mindbird_contao_sis.service.sis:
        class: Mindbird\Contao\SisBundle\Service\Sis
        calls:
            - [updateLeague, ['@?']]
