services:
    _defaults:
            autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    mindbird.service.sis:
        class: Mindbird\Contao\SisBundle\Service\Sis
        calls:
            - [updateLeague, ['@?']]

    mindbird.command.sis.update:
        class: Mindbird\Contao\SisBundle\Command\SisUpdateAllCommand

    mindbird.command.sis.update-league:
        class: Mindbird\Contao\SisBundle\Command\SisUpdateLeagueCommand
        arguments:
            - "@mindbird.service.sis"

